wandb_version: 1

v_lr:
  desc: null
  value: 5.0e-06
u_lr:
  desc: null
  value: 1.0e-05
d_lr:
  desc: null
  value: 5.0e-05
v_grad_norm:
  desc: null
  value: 1.0
u_grad_norm:
  desc: null
  value: 1.0
d_grad_norm:
  desc: null
  value: 1.0
eval_rew:
  desc: null
  value: 0
epochs:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1768854932
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.9
      5: 0.17.6
      8:
      - 5
      - 9
      13: linux-x86_64
